refactor: made Itune Card Generic'
prabhat-wednesday/react-graphql-ts-template pull request #10
Opened 2022-10-06 14:03 UTC by prabhat-wednesday

### Ticket Link

---

### Related Links

---

### Description
Made ITune Song Card Component Generic and solve conflict
---

### Steps to Reproduce / Test

---

---

### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added]
- [ ] Relevant documentation is changed or added (and PR referenced)

### GIF's

---

2022-10-06 14:15 UTC, christin-is-buildding requested changes
1. please add tests
2. Instead of `ItuneCard` let's think of a component that takes in a logo, a title and a subtitle.

2022-10-07 13:24 UTC, christinittyjohn requested changes
1. please try to test failure scenarios
2. we should ensure that the component does it's job. You can do that by checking if the title of the card is rendered to the user. We should try to write tests that matter to users.

2022-10-07 13:24 UTC, christinittyjohn commented on app/components/For/index.tsx
> +  of?: T[] | Song[];
Please revert

2022-10-07 13:24 UTC, christinittyjohn commented on app/components/ItuneCard/index.tsx
> +  cardTitle = 'Card Title'
Important details like the title name etc.. should be required instead of using default values. Also displaying cardTitle is a bit weird. 

Normally in these cards, you'd have the title text itself and the UI will let the user know that the text is the title of that card.

2022-10-07 13:24 UTC, christinittyjohn commented on app/components/ItuneCard/tests/index.test.tsx
> +  it('should render and match the snapshot', () => {
what happens if the song object does not contain the properties that you expect ?

2022-10-07 13:24 UTC, christinittyjohn commented on app/components/ItuneSongList/tests/index.test.tsx
> +  it('should render and match the snapshot', () => {
can we not use renderProvider here ?

what happens if songsData is empty ? Or not an array ?

2022-10-07 13:24 UTC, christinittyjohn commented on app/containers/ItunesContainer/index.tsx
> +// const CustomLabel = styled.label`
please remove usused code

2022-10-10 09:38 UTC, christinittyjohn requested changes

2022-10-10 09:38 UTC, christinittyjohn commented on app/components/ItuneCard/tests/index.test.tsx
> +  it('should render and match the snapshot when song object is empty', () => {
Please add assertions for the UI elements that will be rendered in this case.

2022-10-10 09:38 UTC, christinittyjohn commented on app/components/ItuneSongList/index.tsx
> +    <>
Try to avoid unnecessary Fragments

2022-10-10 09:38 UTC, christinittyjohn commented on app/components/ItuneSongList/tests/index.test.tsx
> +    expect(getByTestId('default-message')).toBeInTheDocument();
Try to expect the text that will be shown to end users

2022-10-10 14:44 UTC, christin-wednesday commented on app/components/ItuneCard/tests/index.test.tsx
> +    expect(getByTestId('cover-img')).toBeInTheDocument();
Why do we render the cover image in this scenario ?

2022-10-10 14:44 UTC, christin-wednesday commented on app/components/ItuneSongList/tests/index.test.tsx
> +import { render } from '@testing-library/react';
Please use render from test utils

2022-10-11 11:42 UTC, christinittyjohn requested changes
please update the gif

2022-10-11 11:42 UTC, christinittyjohn commented on app/components/ItuneCard/index.tsx
> +    <If condition={isEmpty(trackId)}>
Is this intensional ?

2022-10-11 11:44 UTC, prabhat-wednesday commented on app/components/ItuneCard/index.tsx
> +    <If condition={isEmpty(trackId)}>
Yeah

2022-10-11 12:56 UTC, christinittyjohn requested changes

2022-10-11 12:56 UTC, christinittyjohn commented on app/components/ItuneSongList/tests/index.test.tsx
> +    expect(getByTestId('collection-name').textContent).toBe(collectionName);
```suggestion
```

2022-10-11 14:16 UTC, merged