feat: implemented Login form
prabhat-wednesday/react-graphql-ts-template pull request #24
Opened 2022-11-16 06:00 UTC by prabhat-wednesday

### Ticket Link

---

### Related Links

---

### Description
- Add Login Form Container 
---

### Steps to Reproduce / Test

---

---

### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added]
- [ ] Relevant documentation is changed or added (and PR referenced)

### GIF's
![2022-11-16 11 26 10](https://user-images.githubusercontent.com/114152029/202095882-622550b1-9258-4a23-9d55-96ee3a1b7d1d.gif)
![2022-11-16 11 28 49](https://user-images.githubusercontent.com/114152029/202096332-eb088328-79e5-40c5-8541-c0a90be5c6a3.gif)

---

2022-11-16 07:00 UTC, christinittyjohn requested changes

2022-11-16 07:00 UTC, christinittyjohn commented on app/containers/LoginContainer/tests/index.test.tsx
> +describe('<LoginContainer tests', () => {
Please add tests for the functionality.

2022-11-16 13:07 UTC, christinittyjohn commented on app/containers/LoginContainer/index.tsx
> +  { label: 'Username', name: 'username', message: 'Please input your username!' },
Please add support for translations

2022-11-16 13:09 UTC, christinittyjohn requested changes

2022-11-16 13:09 UTC, christinittyjohn commented on app/components/FormInput/index.tsx
> +    <Form.Item label={label} name={name} rules={[{ required: true, message }]}>
This sets every field as required.

2022-11-16 14:23 UTC, prabhat-wednesday commented on app/components/FormInput/index.tsx
> +    <Form.Item label={label} name={name} rules={[{ required: true, message }]}>
shouldn't  every fields to be required

2022-11-17 07:15 UTC, christin-is-buildding requested changes
please improve the tests in FormInput

2022-11-17 07:15 UTC, christin-is-buildding commented on app/containers/App/selector.ts
> +export const selectLoginState = (state: any) => state.loginReducer || initialState;
please move this to the login container

2022-11-17 09:56 UTC, christinittyjohn requested changes

2022-11-17 09:56 UTC, christinittyjohn commented on app/translations/en.json
> +  "label_1": "Username",
please use descriptive keys

2022-11-17 10:20 UTC, christinittyjohn requested changes
please change translation keys for form labels.

2022-11-17 11:13 UTC, christinittyjohn approved these changes

2022-11-17 11:17 UTC, merged