Feat/created UI
prabhat-wednesday/react-graphql-ts-template pull request #4
Opened 2022-09-29 13:55 UTC by prabhat-wednesday

### Ticket Link

---

### Related Links

---

### Description
Created UI and render the data on the screen
---

### Steps to Reproduce / Test

---

---

### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added]
- [ ] Relevant documentation is changed or added (and PR referenced)

### GIF's

---

2022-09-29 14:57 UTC, christin-wednesday requested changes

2022-09-29 14:57 UTC, christin-wednesday commented on app/app.tsx
> +// eslint-disable-next-line import/no-duplicates
```suggestion
```

2022-09-29 14:57 UTC, christin-wednesday commented on app/containers/ItuensContainer/index.tsx
> +      dispatch(getSearchTerm(e.target.value));
let's stick to the dispatch prop that is mapped

2022-09-29 14:57 UTC, christin-wednesday commented on app/containers/ItuensContainer/reducer.ts
> +  dataToShow: [];
we should specify the type of dataToShow.

2022-09-30 07:51 UTC, christin-is-buildding requested changes
please add screen shots

2022-09-30 07:51 UTC, christin-is-buildding commented on app/containers/ItuensContainer/apiUtils.ts
> +const api = create({ baseURL: 'https://itunes.apple.com' });
apiUtils will not be container specific, this should be a separate file in the services folder

2022-09-30 07:51 UTC, christin-is-buildding commented on app/containers/ItuensContainer/index.tsx
> +const ItunesContainer = ({ dispatchArtistName, dataToShow }: any) => {
please add tests

2022-09-30 12:48 UTC, christin-is-buildding approved these changes

2022-09-30 13:24 UTC, merged